### ISSUE TITLE
[BUG]  No module named sherlock.report

### ISSUE THREAD

**Issue by leeuwe** [bhirsz/robotframework-sherlock#49]
git revision installed: f593b3b29962cad74cdacf6a094f7d1ed7d1c237
installation method: as documented (with `pip install .`)

```
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Python39\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Python39\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Python39\lib\site-packages\sherlock\__init__.py", line 2, in <module>
    from sherlock.core import Sherlock
  File "C:\Python39\lib\site-packages\sherlock\core.py", line 8, in <module>
    from sherlock.report import html_report, print_report, json_report
ModuleNotFoundError: No module named 'sherlock.report'
```

site-packages/sherlock contained:
```
|   complexity.py
|   config.py
|   core.py
|   exceptions.py
|   file_utils.py
|   model.py
|   version.py
|   visitor.py
|   __init__.py
|   __main__.py
|
\---__pycache__
        complexity.cpython-39.pyc
        config.cpython-39.pyc
        core.cpython-39.pyc
        exceptions.cpython-39.pyc
        file_utils.cpython-39.pyc
        model.cpython-39.pyc
        version.cpython-39.pyc
        visitor.cpython-39.pyc
        __init__.cpython-39.pyc
        __main__.cpython-39.pyc
```

Please fix pip install

**Comment by leeuwe** [comment]
I fixed it by manually adding the report folder from the git repository, but I thought it's worth logging as an issue.

**Comment by bhirsz** [comment]
Thanks for the report - it's due to missing loading the package in ``setup.py``. I will fix it
