### ISSUE TITLE
[BUG]  Comments on same line as code aren't ignored when parsing

### ISSUE THREAD

**Issue by leeuwe** [bhirsz/robotframework-sherlock#50]
git revision installed: https://github.com/bhirsz/robotframework-sherlock/commit/f593b3b29962cad74cdacf6a094f7d1ed7d1c237

```
Sherlock analysis of Robot Framework code:

Using C:\github.com\my-test as source repository
Loaded C:\github.com\my-test\output.xml output file
Traceback (most recent call last):
  File "C:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\sherlock.exe\__main__.py", line 7, in <module>
  File "C:\python39\lib\site-packages\sherlock\__init__.py", line 19, in run_cli
    raise err
  File "C:\python39\lib\site-packages\sherlock\__init__.py", line 9, in run_cli
    runner.run()
  File "C:\python39\lib\site-packages\sherlock\core.py", line 31, in run
    tree = self.map_resources_for_path(root)
  File "C:\python39\lib\site-packages\sherlock\core.py", line 58, in map_resources_for_path
    tree = Tree.from_directory(path=root, gitignore=self.config.default_gitignore)
  File "C:\python39\lib\site-packages\sherlock\model.py", line 417, in from_directory
    child_tree = cls.from_directory(path=child, gitignore=gitignore)
  File "C:\python39\lib\site-packages\sherlock\model.py", line 430, in from_directory
    tree.children.append(Resource(child))
  File "C:\python39\lib\site-packages\sherlock\model.py", line 338, in __init__
    visitor.visit(model)
  File "C:\python39\lib\ast.py", line 407, in visit
    return visitor(node)
  File "C:\python39\lib\ast.py", line 415, in generic_visit
    self.visit(item)
  File "C:\python39\lib\ast.py", line 407, in visit
    return visitor(node)
  File "C:\python39\lib\ast.py", line 415, in generic_visit
    self.visit(item)
  File "C:\python39\lib\ast.py", line 407, in visit
    return visitor(node)
  File "C:\python39\lib\site-packages\sherlock\model.py", line 172, in visit_Variable
    self.variables[node.name] = node.value[0]  # FIXME arrays and such..by default ${VAR}  1 -> 1 is tuple
  File "C:\python39\lib\site-packages\robot\variables\variables.py", line 37, in __setitem__
    self.store.add(name, value)
  File "C:\python39\lib\site-packages\robot\variables\store.py", line 84, in add
    name, value = self._undecorate_and_validate(name, value)
  File "C:\python39\lib\site-packages\robot\variables\store.py", line 101, in _undecorate_and_validate
    self._raise_cannot_set_type(name, value, 'dictionary')
  File "C:\python39\lib\site-packages\robot\variables\store.py", line 106, in _raise_cannot_set_type
    raise VariableError("Cannot set variable '%s': Expected %s-like value, got %s."
robot.errors.VariableError: Cannot set variable '&{Access}': Expected dictionary-like value, got string.
```

Example:
```
&{Access}         name=value   #inline comment
```

**Comment by bhirsz** [comment]
Hi, thank you for reporting the issue - I see that there is problem with how I parse variables from ``*** Variables ***`` section (I load them just in case they will be needed for importing the resources -> ``Resource  ${VAR}.resource`` for example). It's related to #51

**Comment by leeuwe** [comment]
Yes, sorry, it should've added it came from a `*** variables ***` section, but glad you found it out :-) 
I suggest you close this issue as a duplicate of #51 .

**Comment by bhirsz** [comment]
Let it stay as it was first -> in fact #50 is duplicate, but contains bit other info as well (that could lead to other bugs) so I will keep them both :)
