### ISSUE TITLE
Sherlock does not work with Browser Library atests

### ISSUE THREAD

**Issue by Snooz82** [bhirsz/robotframework-sherlock#51]
Hi Bart,

I wanted to try Sherlock on our atests (Browser lib)

```
❯ sherlock --output results/output.xml .
Sherlock analysis of Robot Framework code:

Using /System/Volumes/Data/Source/MarketSquare/robotframework-browser as source repository
Loaded /System/Volumes/Data/Source/MarketSquare/robotframework-browser/results/output.xml output file
Traceback (most recent call last):
  File "/Users/rener/.pyenv/versions/3.10.0/bin/sherlock", line 33, in <module>
    sys.exit(load_entry_point('robotframework-sherlock', 'console_scripts', 'sherlock')())
  File "/System/Volumes/Data/Source/bhirsz/robotframework-sherlock/sherlock/__init__.py", line 19, in run_cli
    raise err
  File "/System/Volumes/Data/Source/bhirsz/robotframework-sherlock/sherlock/__init__.py", line 9, in run_cli
    runner.run()
  File "/System/Volumes/Data/Source/bhirsz/robotframework-sherlock/sherlock/core.py", line 31, in run
    tree = self.map_resources_for_path(root)
  File "/System/Volumes/Data/Source/bhirsz/robotframework-sherlock/sherlock/core.py", line 58, in map_resources_for_path
    tree = Tree.from_directory(path=root, gitignore=self.config.default_gitignore)
  File "/System/Volumes/Data/Source/bhirsz/robotframework-sherlock/sherlock/model.py", line 417, in from_directory
    child_tree = cls.from_directory(path=child, gitignore=gitignore)
  File "/System/Volumes/Data/Source/bhirsz/robotframework-sherlock/sherlock/model.py", line 417, in from_directory
    child_tree = cls.from_directory(path=child, gitignore=gitignore)
  File "/System/Volumes/Data/Source/bhirsz/robotframework-sherlock/sherlock/model.py", line 417, in from_directory
    child_tree = cls.from_directory(path=child, gitignore=gitignore)
  File "/System/Volumes/Data/Source/bhirsz/robotframework-sherlock/sherlock/model.py", line 430, in from_directory
    tree.children.append(Resource(child))
  File "/System/Volumes/Data/Source/bhirsz/robotframework-sherlock/sherlock/model.py", line 338, in __init__
    visitor.visit(model)
  File "/Users/rener/.pyenv/versions/3.10.0/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/Users/rener/.pyenv/versions/3.10.0/lib/python3.10/ast.py", line 418, in generic_visit
    self.visit(item)
  File "/Users/rener/.pyenv/versions/3.10.0/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/Users/rener/.pyenv/versions/3.10.0/lib/python3.10/ast.py", line 418, in generic_visit
    self.visit(item)
  File "/Users/rener/.pyenv/versions/3.10.0/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/System/Volumes/Data/Source/bhirsz/robotframework-sherlock/sherlock/model.py", line 172, in visit_Variable
    self.variables[node.name] = node.value[0]  # FIXME arrays and such..by default ${VAR}  1 -> 1 is tuple
  File "/Users/rener/.pyenv/versions/3.10.0/lib/python3.10/site-packages/robot/variables/variables.py", line 37, in __setitem__
    self.store.add(name, value)
  File "/Users/rener/.pyenv/versions/3.10.0/lib/python3.10/site-packages/robot/variables/store.py", line 84, in add
    name, value = self._undecorate_and_validate(name, value)
  File "/Users/rener/.pyenv/versions/3.10.0/lib/python3.10/site-packages/robot/variables/store.py", line 101, in _undecorate_and_validate
    self._raise_cannot_set_type(name, value, 'dictionary')
  File "/Users/rener/.pyenv/versions/3.10.0/lib/python3.10/site-packages/robot/variables/store.py", line 106, in _raise_cannot_set_type
    raise VariableError("Cannot set variable '%s': Expected %s-like value, got %s."
robot.errors.VariableError: Cannot set variable '&{expected get json body}': Expected dictionary-like value, got string.
Fatal exception occurred. You can create an issue at https://github.com/bhirsz/robotframework-sherlock/issues . Thanks!
```
cheers

**Comment by Snooz82** [comment]
So reproduction is basically:

- Clone Browser
- follow contribution guidelines
- run `inv atest` in the virtual environment 

Take the output.xml  with sherlock and see the firework 💥💣❤️‍🔥

**Comment by bhirsz** [comment]
Thanks, just quick glance on error stack is telling me that my primitive variable handling (with FIXME comment) is in fact, very primitive ;) I will try to reuse RF internal handling of `` *** Variables ***`` section to fix this issue. And I will try Sherlock with your atests to see if there are any other suprises, thanks!

**Comment by bhirsz** [comment]
So I won the battle but not the war ;)

**Comment by bhirsz** [comment]
@Snooz82 Browser is certainly funky but I'm not sure it's 100% because of Sherlock - I was getting embedded variables errors, then after restarting the PC I was getting import browser on Browser library (due to missing rfbrowser init -> even if it worked previously). Then I managed to get it working:
```
Directory: Browser
    Library: Browser
    Import errors:
        Failed to load library with an error: Variable '${PLAYWRIGHT_TIMEOUT}' not found. You can provide Robot variables to Sherlock using -v/--variable name:value cli option.
      Timings:
        Total elapsed    Shortest execution    Longest execution    Average execution
        01:05:01:165     00:00:00:007          00:03:43:878         00:00:05:903

      Keywords:
        +------------------------------------+------------+--------------+
        | Keyword                            | Executions |   Elapsed    |
        +------------------------------------+------------+--------------+
        | Add Cookie                         |     15     | 00:00:00:303 |
        | Add Style Tag                      |     3      | 00:00:00:654 |
        | Check Checkbox                     |     3      | 00:00:01:389 |
        | Clear Permissions                  |     1      | 00:00:00:008 |
        | Clear Text                         |     4      | 00:00:00:186 |
        | Click                              |    101     | 00:00:25:660 |
        | Close Browser                      |     81     | 00:00:20:726 |
        | Close Context                      |     23     | 00:00:03:216 |
        | Close Page                         |     29     | 00:00:04:677 |
        | Connect To Browser                 |     1      | 00:00:00:054 |
        | Crawl Site                         |     3      | 00:00:05:818 |
        | Delete All Cookies                 |     2      | 00:00:00:011 |
        | Deselect Options                   |     2      | 00:00:00:088 |
        | Download                           |     2      | 00:00:00:491 |
        | Drag And Drop                      |     6      | 00:00:01:156 |
        | Drag And Drop By Coordinates       |     2      | 00:00:08:596 |
        | Drag And Drop Relative To          |     4      | 00:00:00:480 |
        | Eat All Cookies                    |     1      | 00:00:00:007 |
        | Evaluate JavaScript                |     14     | 00:00:01:139 |
        | Execute JavaScript                 |     4      | 00:00:00:636 |
        | Fill Secret                        |     15     | 00:00:00:512 |
        | Fill Text                          |     6      | 00:00:00:100 |
        | Focus                              |     6      | 00:00:00:482 |
        | Get Attribute                      |     10     | 00:00:00:251 |
        | Get Attribute Names                |     7      | 00:00:00:755 |
        | Get BoundingBox                    |     37     | 00:00:02:188 |
        | Get Browser Catalog                |     5      | 00:00:00:091 |
        | Get Browser Ids                    |     10     | 00:00:00:119 |
        | Get Checkbox State                 |     9      | 00:00:00:305 |
        | Get Classes                        |     5      | 00:00:00:146 |
        | Get Client Size                    |     11     | 00:00:00:669 |
        | Get Context Ids                    |     12     | 00:00:00:115 |
        | Get Cookie                         |     6      | 00:00:00:087 |
        | Get Cookies                        |     10     | 00:00:00:103 |
        | Get Device                         |     3      | 00:00:00:060 |
        | Get Devices                        |     1      | 00:00:00:016 |
        | Get Element                        |     16     | 00:00:02:158 |
        | Get Element Count                  |     16     | 00:00:01:309 |
        | Get Elements                       |     6      | 00:00:05:315 |
        | Get Element State                  |     5      | 00:00:00:938 |
        | Get Element States                 |     34     | 00:00:06:488 |
        | Get Page Ids                       |     8      | 00:00:00:570 |
        | Get Page Source                    |     1      | 00:00:00:008 |
        | Get Property                       |     17     | 00:00:01:115 |
        | Get Scroll Position                |     22     | 00:00:02:561 |
        | Get Scroll Size                    |     6      | 00:00:00:132 |
        | Get Selected Options               |     20     | 00:00:05:160 |
        | Get Select Options                 |     6      | 00:00:01:805 |
        | Get Style                          |     18     | 00:00:01:162 |
        | Get Table Cell Element             |     11     | 00:00:01:392 |
        | Get Table Cell Index               |     8      | 00:00:00:246 |
        | Get Table Row Index                |     16     | 00:00:00:975 |
        | Get Text                           |    174     | 00:00:12:707 |
        | Get Title                          |     65     | 00:00:03:035 |
        | Get Url                            |     34     | 00:00:01:026 |
        | Get Viewport Size                  |     8      | 00:00:00:062 |
        | Go Back                            |     2      | 00:00:00:128 |
        | Go Forward                         |     2      | 00:00:00:057 |
        | Go To                              |     97     | 00:00:21:889 |
        | Grant Permissions                  |     2      | 00:00:00:078 |
        | Handle Future Dialogs              |     3      | 00:00:00:031 |
        | Highlight Elements                 |     6      | 00:00:00:176 |
        | Hover                              |     10     | 00:00:01:191 |
        | Http                               |     12     | 00:00:00:146 |
        | Keyboard Input                     |     2      | 00:00:00:068 |
        | Keyboard Key                       |     8      | 00:00:00:066 |
        | LocalStorage Clear                 |     2      | 00:00:00:010 |
        | LocalStorage Get Item              |     10     | 00:00:00:076 |
        | LocalStorage Remove Item           |     2      | 00:00:00:020 |
        | LocalStorage Set Item              |     6      | 00:00:00:148 |
        | Mouse Button                       |     42     | 00:00:05:381 |
        | Mouse Move                         |     5      | 00:00:00:095 |
        | Mouse Move Relative To             |     27     | 00:00:01:467 |
        | New Browser                        |    115     | 00:02:10:442 |
        | New Context                        |     97     | 00:00:27:220 |
        | New Page                           |    399     | 00:03:43:878 |
        | Open Browser                       |     1      | 00:00:01:778 |
        | Press Keys                         |     6      | 00:00:01:017 |
        | Promise To                         |     20     | 00:00:00:314 |
        | Promise To Upload File             |     0      |              |
        | Promise To Wait For Download       |     2      | 00:00:00:018 |
        | Record Selector                    |     0      |              |
        | Register Keyword To Run On Failure |     18     | 00:00:00:174 |
        | Reload                             |     0      |              |
        | Save Storage State                 |     1      | 00:00:00:580 |
        | Scroll By                          |     9      | 00:00:01:076 |
        | Scroll To                          |     19     | 00:00:02:614 |
        | Scroll To Element                  |     8      | 00:00:00:626 |
        | Select Options By                  |     38     | 00:00:21:709 |
        | SessionStorage Clear               |     2      | 00:00:00:014 |
        | SessionStorage Get Item            |     6      | 00:00:00:059 |
        | SessionStorage Remove Item         |     1      | 00:00:00:011 |
        | SessionStorage Set Item            |     5      | 00:00:00:233 |
        | Set Assertion Formatters           |     7      | 00:00:00:050 |
        | Set Browser Timeout                |     73     | 00:00:00:415 |
        | Set Geolocation                    |     5      | 00:00:00:075 |
        | Set Offline                        |     1      | 00:00:00:039 |
        | Set Retry Assertions For           |     12     | 00:00:00:021 |
        | Set Strict Mode                    |     96     | 00:00:00:137 |
        | Set Viewport Size                  |     1      | 00:00:00:009 |
        | Switch Browser                     |     3      | 00:00:00:022 |
        | Switch Context                     |     5      | 00:00:00:032 |
        | Switch Page                        |     9      | 00:00:00:204 |
        | Take Screenshot                    |     14     | 00:00:03:576 |
        | Type Secret                        |     18     | 00:00:09:362 |
        | Type Text                          |     21     | 00:00:06:406 |
        | Uncheck Checkbox                   |     2      | 00:00:01:311 |
        | Upload File By Selector            |     5      | 00:00:39:882 |
        | Wait For                           |     18     | 00:00:04:329 |
        | Wait For Alert                     |     0      |              |
        | Wait For All Promises              |     0      |              |
        | Wait For Elements State            |     42     | 00:00:17:140 |
        | Wait For Function                  |     1      | 00:00:00:063 |
        | Wait For Navigation                |     6      | 00:00:02:714 |
        | Wait For Request                   |     4      | 00:00:00:685 |
        | Wait For Response                  |     4      | 00:00:01:261 |
        | Wait Until Network Is Idle         |     1      | 00:00:01:184 |
        +------------------------------------+------------+--------------+
```
I will be using your tests for further investigations to see if I get any reproducible errors and also to enhance our analysis
